packages:
  - "apps/*"
  - "packages/*"
  - "tools/*"

# Catalog for shared dependencies
catalog:
  # React ecosystem
  react: ^18.2.0
  react-dom: ^18.2.0
  "@types/react": ^18.2.45
  "@types/react-dom": ^18.2.18

  # Next.js ecosystem
  next: ^14.0.4
  "@next/eslint-config-next": ^14.0.4

  # TypeScript
  typescript: ^5.3.3
  "@types/node": ^20.10.6

  # Styling
  tailwindcss: ^3.4.0
  "@tailwindcss/forms": ^0.5.7
  "@tailwindcss/typography": ^0.5.10
  autoprefixer: ^10.4.16
  postcss: ^8.4.32

  # UI Components
  "@radix-ui/react-accordion": ^1.1.2
  "@radix-ui/react-alert-dialog": ^1.0.5
  "@radix-ui/react-avatar": ^1.0.4
  "@radix-ui/react-button": ^0.1.0
  "@radix-ui/react-card": ^0.1.0
  "@radix-ui/react-checkbox": ^1.0.4
  "@radix-ui/react-dialog": ^1.0.5
  "@radix-ui/react-dropdown-menu": ^2.0.6
  "@radix-ui/react-form": ^0.0.3
  "@radix-ui/react-hover-card": ^1.0.7
  "@radix-ui/react-icons": ^1.3.0
  "@radix-ui/react-label": ^2.0.2
  "@radix-ui/react-menubar": ^1.0.4
  "@radix-ui/react-navigation-menu": ^1.1.4
  "@radix-ui/react-popover": ^1.0.7
  "@radix-ui/react-progress": ^1.0.3
  "@radix-ui/react-radio-group": ^1.1.3
  "@radix-ui/react-scroll-area": ^1.0.5
  "@radix-ui/react-select": ^2.0.0
  "@radix-ui/react-separator": ^1.0.3
  "@radix-ui/react-sheet": ^0.1.0
  "@radix-ui/react-slider": ^1.1.2
  "@radix-ui/react-switch": ^1.0.3
  "@radix-ui/react-table": ^0.1.0
  "@radix-ui/react-tabs": ^1.0.4
  "@radix-ui/react-toast": ^1.1.5
  "@radix-ui/react-toggle": ^1.0.3
  "@radix-ui/react-tooltip": ^1.0.7
  "class-variance-authority": ^0.7.0
  clsx: ^2.0.0
  "tailwind-merge": ^2.2.0
  "lucide-react": ^0.303.0

  # Data fetching & state management
  "@tanstack/react-query": ^5.17.9
  "@tanstack/react-query-devtools": ^5.17.9
  "@tanstack/react-table": ^8.11.6
  zustand: ^4.4.7
  swr: ^2.2.4

  # Forms & validation
  "react-hook-form": ^7.48.2
  "@hookform/resolvers": ^3.3.2
  zod: ^3.22.4

  # Charts & visualization
  recharts: ^2.8.0
  "react-chartjs-2": ^5.2.0
  "chart.js": ^4.4.1
  d3: ^7.8.5
  "@types/d3": ^7.4.3

  # Date & time
  "date-fns": ^3.0.6
  "react-day-picker": ^8.10.0

  # Utilities
  lodash: ^4.17.21
  "@types/lodash": ^4.14.202
  "use-debounce": ^10.0.0
  "react-use": ^17.4.2
  cronstrue: ^2.41.0

  # WebSocket & real-time
  "socket.io-client": ^4.7.4
  ws: ^8.16.0
  "@types/ws": ^8.5.10

  # Authentication
  "next-auth": ^4.24.5
  "@auth/prisma-adapter": ^1.0.15

  # Development tools
  eslint: ^8.56.0
  "@typescript-eslint/eslint-plugin": ^6.17.0
  "@typescript-eslint/parser": ^6.17.0
  "eslint-config-prettier": ^9.1.0
  "eslint-plugin-react": ^7.33.2
  "eslint-plugin-react-hooks": ^4.6.0
  "eslint-plugin-tailwindcss": ^3.13.1
  prettier: ^3.1.1
  "prettier-plugin-tailwindcss": ^0.5.10

  # Testing
  "@testing-library/react": ^14.1.2
  "@testing-library/jest-dom": ^6.2.0
  "@testing-library/user-event": ^14.5.1
  jest: ^29.7.0
  "jest-environment-jsdom": ^29.7.0
  "@types/jest": ^29.5.11
  "ts-jest": ^29.1.1

# Shared configuration
shared:
  # Node version requirement
  engines:
    node: ">=18.0.0"
    pnpm: ">=8.0.0"

  # Common peer dependencies
  peerDependencies:
    react: "^18.2.0"
    react-dom: "^18.2.0"
