apiVersion: v1
kind: ConfigMap
metadata:
  name: footy-brain-config
  namespace: footy-brain
data:
  # Application configuration
  ENVIRONMENT: "production"
  API_HOST: "0.0.0.0"
  API_PORT: "8000"
  
  # Worker configuration
  LIVE_WORKER_INTERVAL: "10"
  LIVE_WORKER_CONCURRENCY: "5"
  FRAME_WORKER_INTERVAL: "60"
  CELERY_WORKER_CONCURRENCY: "4"
  
  # Database configuration
  DATABASE_URL: "postgresql://footy:$(DB_PASSWORD)@postgres:5432/footy"
  REDIS_URL: "redis://redis:6379/0"
  CELERY_BROKER_URL: "redis://redis:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis:6379/2"
  
  # Frontend configuration
  NEXT_PUBLIC_API_URL: "https://api.footy-brain.com"
  NEXT_PUBLIC_WS_URL: "wss://api.footy-brain.com"
  NEXTAUTH_URL: "https://dashboard.footy-brain.com"

---
apiVersion: v1
kind: Secret
metadata:
  name: footy-brain-secrets
  namespace: footy-brain
type: Opaque
stringData:
  # Database password
  DB_PASSWORD: "footy_secure_2024"
  
  # API keys
  RAPIDAPI_KEY: "your_rapidapi_key_here"
  
  # JWT secrets
  JWT_SECRET: "footy_jwt_secret_2024"
  NEXTAUTH_SECRET: "footy_nextauth_secret_2024"
